/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.time.LocalTime;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Opcion;
import modelo.PersistenciaPreguntas;
import modelo.Pregunta;

/**
 *
 * @author T-101
 */
public class TestAplicacion extends javax.swing.JFrame {
int numero=0,npreg=0,cronometro=0;
    /**
     * Creates new form TestAplicacion
     */
    public TestAplicacion() {
        initComponents();
        setLocationRelativeTo(this); // Este método centra la ventana
        setSize(400,500);
        mostrarPregunta(numero++);
        // Creando el tiempo
        Thread t1 = new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    cronometro -= 1;
                    etiquetaTiempo.setText("Tiempo: " + cronometro);
                    try {
                        Thread.sleep(1000);
                        if(cronometro==0)mostrarPregunta(numero++);
                    } catch (InterruptedException ex) {

                    }
                }
            }
        });
        t1.start();
    }
    public void mostrarPregunta(int numero)
    {
        cronometro = 31;
        try
        {
            // Primero sacamos la pregunta de l número dado
            ArrayList<Pregunta> preguntas=PersistenciaPreguntas.leer();
            Pregunta p=preguntas.get(numero);
            // Ajustamos valores
            // Preimero va el título
            etiquetaPregunta.setText(p.getTitulo());
            // Ahora las opciones
            ArrayList<Opcion> opciones=p.getOpciones();
            // Aplicamos el algoritmo
            opciones=PersistenciaPreguntas.opcionesAleatorias(opciones);
            rb1.setText(opciones.get(0).getTitulo());
            rb2.setText(opciones.get(1).getTitulo());
            rb2.setText(opciones.get(2).getTitulo());
            rb2.setText(opciones.get(3).getTitulo());
            npreg++;
        }catch(Exception ex)
        {
            
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        etiquetaTiempo = new javax.swing.JLabel();
        etiquetaPregunta = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(22, 193, 22));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Ratchet y Clank (PS2-PS3)");
        jPanel1.add(jLabel2);

        etiquetaTiempo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiquetaTiempo.setText("Tiempo:");
        jPanel1.add(etiquetaTiempo);

        etiquetaPregunta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiquetaPregunta.setText("Pregunta");
        jPanel1.add(etiquetaPregunta);

        rb1.setBackground(new java.awt.Color(22, 193, 22));
        buttonGroup1.add(rb1);
        rb1.setText("jRadioButton1");
        jPanel1.add(rb1);

        rb2.setBackground(new java.awt.Color(22, 193, 22));
        buttonGroup1.add(rb2);
        rb2.setText("jRadioButton2");
        jPanel1.add(rb2);

        rb3.setBackground(new java.awt.Color(22, 193, 22));
        buttonGroup1.add(rb3);
        rb3.setText("jRadioButton3");
        jPanel1.add(rb3);

        rb4.setBackground(new java.awt.Color(22, 193, 22));
        buttonGroup1.add(rb4);
        rb4.setText("jRadioButton4");
        jPanel1.add(rb4);

        jButton1.setText("Siguiente pregunta >>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Siguiente pregunta >>
        mostrarPregunta(numero);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestAplicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel etiquetaPregunta;
    private javax.swing.JLabel etiquetaTiempo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    // End of variables declaration//GEN-END:variables
}
