/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.time.LocalTime;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JRadioButton;
import modelo.Opcion;
import modelo.PersistenciaPreguntas;
import modelo.Pregunta;

/**
 *
 * @author T-101
 */
public class TestAplicacion extends javax.swing.JFrame {

    public static int numero = 0, npreg = 0, cronometro = 0, i = 0, click = 0;
    short aux = 0;

    /**
     * Creates new form TestAplicacion
     */
    public TestAplicacion() {
        initComponents();
        setLocationRelativeTo(this); // Este método centra la ventana
        setSize(400, 500);
        mostrarPregunta(numero++);
        // Creando el tiempo
        Thread t1 = new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    cronometro -= 1;
                    etiquetaTiempo.setText("Tiempo: " + cronometro);
                    try {
                        Thread.sleep(1000);
                        if (cronometro == 0) {
                            mostrarPregunta(numero++);
                        }
                    } catch (InterruptedException ex) {

                    }
                }
            }
        });
        t1.start();
    }
public String checarSeleccionada(){
 
 String rText=rb1.getText();
    JRadioButton ra1=(JRadioButton) buttonGroup1.getSelection().getSelectedObjects()[0];
    System.out.println("rb1 "+ra1.getText());
 return null;
}
    public void mostrarPregunta(int numero) {
        cronometro = 31;
        try {
            // Primero sacamos la pregunta de l número dado
            if (aux == 0) {
                for (Pregunta p : PersistenciaPreguntas.leer()) {
                    i++;
                }
            }
            aux++;

            ArrayList<Pregunta> preguntas = PersistenciaPreguntas.leer();
            Pregunta p = preguntas.get(numero);

            // Ajustamos valores
            // Preimero va el título
            npreg++; // Variable clave
            etiquetaPregunta.setText(npreg + ".- " + p.getTitulo() + " " + npreg + "/" + i);
            // Ahora las opciones
            ArrayList<Opcion> opciones = p.getOpciones();
            // Aplicamos el algoritmo
            opciones = PersistenciaPreguntas.opcionesAleatorias(opciones);
            rb1.setText(opciones.get(0).getTitulo());
            rb2.setText(opciones.get(1).getTitulo());
            rb3.setText(opciones.get(2).getTitulo());
            rb4.setText(opciones.get(3).getTitulo());

        } catch (Exception ex) {

        }

    }

    public void Resultados() {
        Resultados resultado = new Resultados();
        resultado.setVisible(true);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        etiquetaTiempo = new javax.swing.JLabel();
        etiquetaPregunta = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(22, 193, 22));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Ratchet y Clank (PS2-PS3)");
        jPanel1.add(jLabel2);

        etiquetaTiempo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiquetaTiempo.setText("Tiempo:");
        jPanel1.add(etiquetaTiempo);

        etiquetaPregunta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiquetaPregunta.setText("Pregunta");
        jPanel1.add(etiquetaPregunta);

        rb1.setBackground(new java.awt.Color(22, 193, 22));
        rb1.setText("jRadioButton1");
        jPanel1.add(rb1);

        rb2.setBackground(new java.awt.Color(22, 193, 22));
        rb2.setText("jRadioButton2");
        jPanel1.add(rb2);

        rb3.setBackground(new java.awt.Color(22, 193, 22));
        rb3.setText("jRadioButton3");
        jPanel1.add(rb3);

        rb4.setBackground(new java.awt.Color(22, 193, 22));
        rb4.setText("jRadioButton4");
        jPanel1.add(rb4);

        jButton1.setText("Siguiente pregunta >>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Siguiente pregunta >>
        
        System.out.println("Seleccionada es "+checarSeleccionada());
     /*   click++;
        mostrarPregunta(numero++);
        if (click == i) {
            Resultados();
        }*/
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestAplicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel etiquetaPregunta;
    private javax.swing.JLabel etiquetaTiempo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    // End of variables declaration//GEN-END:variables
}


